---
# tasks file for battleships

# - name: Time for a new game
#   template:
#     dest: battleship_game_stats.yml
#     src: files/new_game.j2
#   when: new_game|default(False)|bool

- name: Check requirements to play are met
  include_tasks: requirements.yml

- name: Fire at ships
  include_tasks: shoot.yml
  loop: "{{ ships }}"
  loop_control:
    loop_var: ship
    label: "{{ ship.name }}"
  when: shots | list
