---
# tasks file for battleships

- name: New game - removing old game data
  file:
    path: "{{ battleships_data_file }}"
    state: absent
  when: battleships_new_game | bool

- name: Check for existing game data
  stat:
    path: "{{ battleships_data_file }}"
  register: battleships_game_data
  when: not battleships_new_game | bool

- name: New game - setup new game data
  vars:
    shots_fired: "{{ shots_fired_default }}"
    ship_damage: "{{ damage_default }}"
    ship_sunk: "{{ sunk_default }}"
  template:
    dest: "{{ battleships_data_file }}"
    src: ansible_battleships_game_data.yml.j2
  register: game_preparation
  when: (battleships_new_game | bool) or (not battleships_game_data.stat.exists | bool)

- name: New game - confirm new game data
  stat:
    path: "{{ battleships_data_file }}"
  register: battleships_game_data
  when: battleships_new_game | bool


# - name: Check requirements to play are met
#   include_tasks: requirements.yml
# - name: Prepare for new game
#   include_tasks: ship_status.yml
#   loop: "{{ ships }}"
#   loop_control:
#     loop_var: ship
#     label: "{{ ship.name }}"
#   register: game_preparation
#   when: 
#     - shots | list
#     - battleships_game_data.stat.exists | bool
#     - new_game_setup is changed

- name: Fire shots
  vars:
    new_game_setup: completed
  include_tasks: ship_status.yml
  loop: "{{ ships }}"
  loop_control:
    loop_var: ship
    label: "{{ ship.name }}"
  when: 
    - shots | list
    - game_preparation is succeeded
    - battleships_game_data.stat.exists | bool

# - name: Game Over!
#   fail:
#     msg: All your ships are sunk and you don't have a valid spysub access code!
#   when:
#     - ansible_facts.battleships.game_data.carrier.sunk | bool
#     - ansible_facts.battleships.game_data.battleship.sunk | bool
#     - ansible_facts.battleships.game_data.destroyer.sunk | bool
#     - ansible_facts.battleships.game_data.submarine.sunk | bool
#     - ansible_facts.battleships.game_data.patrolboat.sunk | bool
    # spysub1 and spysub2 not enabled