---

- name: Transmitting Spysub1 access code to HQ for validation...
  set_fact:
    spysub1_approvalcode: "{{ approval_codes | random }}"
  no_log: True

- name: Transmitting Spysub2 access code to HQ for validation...
  set_fact:
    spysub2_approvalcode: "{{ approval_codes | random }}"
  no_log: True

- name: Battle Stations!
  set_fact:
    ship_damage: 0

- name: Initializing radar...
  set_fact:
    ship_sunk: False

- name: Shots detected on radar
  debug:
    msg: Radar has detected rounds are in the air
  when: shots is defined

- name: WARNING!! Incoming shells on approach to our {{ ship.name }}!!
  pause:
    seconds: 2
    prompt: |

      Shot number {{ shot_number }} has hit {{ ship.name }}  at grid {{ shot }}!!
  when: shot in ship.location
  changed_when: shot in ship.location
  loop: "{{ shots | from_yaml }}"
  loop_control:
    loop_var: shot
    label: "Shot number {{ shot_number }}"
    index_var: shot_number

- name: Excellent. These shells completely missed our {{ ship.name }}
  debug:
    msg: "Shot number {{ shot_number }} has missed!!"
  when: shot not in ship.location
  changed_when: shot not in ship.location
  loop: "{{ shots | from_yaml }}"
  loop_control:
    loop_var: shot
    label: "Shot number {{ shot_number }}"
    index_var: shot_number


- name: Damage reports are in!
  debug:
    msg: "Commander, {{ ship.name |  title }} is still functional. Crew report indicates {{ ship_damage }}/{{ ship.health }} health lost"
  when:
    - ship_damage|int != ship.health|int

- name: URGENT SITREP REQUIRED!
  when: ship_sunk | bool
  block:

    - name: Missing SITREP! Request recon of {{ ship.name|title }}!
      pause:
        seconds: 2
        prompt: |

          Commander, this is Charlie-One-Zulu, request for air recon of {{ ship.name|title }} received, standby...

    - name: Recon in progress
      pause:
          seconds: 3
          prompt: |

            Recon of {{ ship.name|title }} in progress,
            Standby.....

    - name: Recon of {{ ship.name|title }} complete...
      pause:
        seconds: 5
        prompt: |

          Commander, we are at the last known location of the {{ ship.name|title }}...
          grid {{ ship.location }}, there is no sign of it.

    - name: SITREP | {{ ship.name }}  has been sunk...
      fail:
        msg: "Bumbow... {{ ship.name }}  is sleeping with the fishes... :`("
      when: ship_sunk | bool

  rescue:

    - name: Spysub1 access code validation received... Decoding
      set_fact:
        game_data:
          spysub1:
            enabled: true
      when: spysub1_approvalcode == spysub1_accesscode

    - name: Spysub1 access code decoded
      debug:
        msg: Spysub1 approved. 1 bonus shot available for next turn only.
      when: game_data.spysub1.enabled | bool

    - name: Spysub2 access code validation received... Decoding
      set_fact:
        game_data:
          spysub2:
            enabled: true
      when: spysub2_approvalcode == spysub2_accesscode

    - name: Spysub2 access code decoded
      debug:
        msg: Spysub2 approved. 2 bonus shots available for next turn only.
      when: game_data.spysub2.enabled | bool

    - name: WARNING!!
      pause:
        seconds: 10
        prompt: |

          "NOTE: You have 10 seconds to communicate this bonus to the other player."
      when: 
        - game_data.spysub1.enabled | bool
        - game_data.spysub2.enabled | bool

    - name: No bonus for you.
      fail:
        msg: Spysub1 and spysub2 approval denied.
      when: 
        - not game_data.spysub1.enabled | bool
        - not game_data.spysub2.enabled | bool
      ignore_errors: True
