name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install software requirements for QA
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip --version
        pip install molecule
        molecule --version
    - name: Molecule lint
      run: molecule lint
