name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install software requirements for QA
      run: |
        python --version
        pip --version
        python -m pip install virtualenv
        python -m virtualenv --version
        python -m virtualenv ansible_venv
        source ansible_venv/bin/activate
        pip install molecule
        molecule --version
    - name: Molecule lint
      run: |
        docker run --rm -it -v "$(pwd)":/tmp/$(basename "${PWD}"):ro -v /var/run/docker.sock:/var/run/docker.sock -w /tmp/$(basename "${PWD}") quay.io/ansible/molecule:2.20 molecule test
