name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install software requirements for QA
      run: |
        python --version
        pip --version
        python -m pip install virtualenv
        virtualenv --version
        virtualenv ansible_venv
        source ansible_venv/bin/activate
        pip install molecule
        molecule --version
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
